# -*- coding: utf-8 -*-

from zope.i18nmessageid import MessageFactory
from senaite.patient.catalog import PATIENT_CATALOG  # noqa

_ = MessageFactory("senaite.patient")

PRODUCT_NAME = "senaite.patient"

DEFAULT_ROLES = ("Manager", )

DEFAULT_TYPES = ("PatientFolder", "Patient", )

AUTO_ID_MARKER = "-- autogenerated --"

GENDERS = (
    ("m", _("Male")),
    ("f", _("Female")),
    ("d", _("Diverse")),
    ("", _("Not Specified")),
)

NAME_ENTRY_MODES = (
    ("parts", _("First name + last name")),
    ("full", _("Fullname")),
)
