# -*- coding: utf-8 -*-
#
# This file is part of SENAITE.PATIENT.
#
# SENAITE.PATIENT is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright 2020-2022 by it's authors.
# Some rights reserved, see README and LICENSE.

from zope.i18nmessageid import MessageFactory
from senaite.patient.catalog import PATIENT_CATALOG  # noqa

_ = MessageFactory("senaite.patient")

PRODUCT_NAME = "senaite.patient"

DEFAULT_ROLES = ("Manager", )

DEFAULT_TYPES = ("PatientFolder", "Patient", )

AUTO_ID_MARKER = "-- autogenerated --"

SEXES = (
    ("m", _("Male")),
    ("f", _("Female")),
    ("", _("Not specified")),
)

GENDERS = (
    ("m", _("Man")),
    ("f", _("Woman")),
    ("t", _("Transgender")),
    ("d", _("Diverse")),
    ("", _("Not Specified")),
)

NAME_ENTRY_MODES = (
    ("parts", _("First name + last name")),
    ("full", _("Fullname")),
)


IDENTIFIERS = (
    (u"passport_id", _(u"Passport ID")),
    (u"national_id", _(u"National ID")),
    (u"driver_id", _(u"Driver ID")),
    (u"voter_id", _(u"Voter ID")),
)

# https://hl7.org/fhir/us/core/ValueSet-detailed-ethnicity.html#expansion
RACES = (
    ("1002-5", _(u"American Indian or Alaska Native")),
    ("2028-9", _(u"Asian")),
    ("2054-5", _(u"Black or African American")),
    ("2076-8", _(u"Native Hawaiian or Other Pacific Islander")),
    ("2106-3", _(u"White")),
    ("2131-1", _(u"Other Race")),
    ("ASKU", _(u"asked but unknown")),
    ("UNK", _(u"unknown")),
)

# https://hl7.org/fhir/us/core/ValueSet-detailed-ethnicity.html#expansion
ETHNICITIES = (
    ("2137-8", _(u"Spaniard")),
    ("2138-6", _(u"Andalusian")),
    ("2139-4", _(u"Asturian")),
    ("2140-2", _(u"Castillian")),
    ("2141-0", _(u"Catalonian")),
    ("2142-8", _(u"Belearic Islander")),
    ("2143-6", _(u"Gallego")),
    ("2144-4", _(u"Valencian")),
    ("2145-1", _(u"Canarian")),
    ("2146-9", _(u"Spanish Basque")),
    ("2148-5", _(u"Mexican")),
    ("2149-3", _(u"Mexican American")),
    ("2150-1", _(u"Mexicano")),
    ("2151-9", _(u"Chicano")),
    ("2152-7", _(u"La Raza")),
    ("2153-5", _(u"Mexican American Indian")),
    ("2155-0", _(u"Central American")),
    ("2156-8", _(u"Costa Rican")),
    ("2157-6", _(u"Guatemalan")),
    ("2158-4", _(u"Honduran")),
    ("2159-2", _(u"Nicaraguan")),
    ("2160-0", _(u"Panamanian")),
    ("2161-8", _(u"Salvadoran")),
    ("2162-6", _(u"Central American Indian")),
    ("2163-4", _(u"Canal Zone")),
    ("2165-9", _(u"South American")),
    ("2166-7", _(u"Argentinean")),
    ("2167-5", _(u"Bolivian")),
    ("2168-3", _(u"Chilean")),
    ("2169-1", _(u"Colombian")),
    ("2170-9", _(u"Ecuadorian")),
    ("2171-7", _(u"Paraguayan")),
    ("2172-5", _(u"Peruvian")),
    ("2173-3", _(u"Uruguayan")),
    ("2174-1", _(u"Venezuelan")),
    ("2175-8", _(u"South American Indian")),
    ("2176-6", _(u"Criollo")),
    ("2178-2", _(u"Latin American")),
    ("2180-8", _(u"Puerto Rican")),
    ("2182-4", _(u"Cuban")),
    ("2184-0", _(u"Dominican")),
    ("ASKU", _(u"asked but unknown")),
    ("OTH", _(u"other")),
    ("UNK", _(u"unknown")),
)
